name: Deploy Node.js app with Express and Socket.io

on:
  # Ejecuta el workflow cuando haya cambios en la rama "main"
  push:
    branches: ["main"]

  # Permite ejecutar manualmente este workflow desde la pestaña "Actions"
  workflow_dispatch:

jobs:
  # Job para construir y desplegar la aplicación
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configurar Node.js versión 20
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Asegura el uso de Node.js versión 20

      # Cachear los módulos de node para mejorar el rendimiento
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # Ejecutar pruebas (opcional)
      - name: Run tests
        run: npm test

      # iniciar la aplicación
      - name: Run start
        run: npm start

      # Subir al repositorio de GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cliente  # Directorio donde está el contenido a desplegar en GitHub Pages
